//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSyncer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\Photos\\Photos\\Static\\Marriage.Mine\\DNet\\CARD 1")]
        public string Folder1 {
            get {
                return ((string)(this["Folder1"]));
            }
            set {
                this["Folder1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\Photos\\Photos\\Static\\Marriage.Mine\\DNet\\CARD 2")]
        public string Folder2 {
            get {
                return ((string)(this["Folder2"]));
            }
            set {
                this["Folder2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\Photos\\Photos\\Static\\Marriage.Mine\\DNet\\CARD 3")]
        public string Folder3 {
            get {
                return ((string)(this["Folder3"]));
            }
            set {
                this["Folder3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\Photos\\Photos\\Static\\Marriage.Mine\\DNet\\CARD 3")]
        public string Folder4 {
            get {
                return ((string)(this["Folder4"]));
            }
            set {
                this["Folder4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P:\\Photos\\Photos\\Static\\Marriage.Mine\\DNet\\CARD 3")]
        public string Folder5 {
            get {
                return ((string)(this["Folder5"]));
            }
            set {
                this["Folder5"] = value;
            }
        }
    }
}
